### ISSUE TITLE
Don't throw IOError for missing .env file

### ISSUE THREAD

**Issue by lachlancooper** [sloria/environs#10]
First of all thanks very much for this beautiful library, I'm using it to replace a few others as well as a lot of manual type-casting.

I would like to suggest making `read_env()` only opportunistically search for a `.env` file, and do nothing (or perhaps log a warning) if no file is found. This is the way django-environ, envparse, and python-dotenv all work.

I think it makes sense to support `.env` files in situations where there is no better way to manage environment variables, such as running an application locally, but not _require_ them when running in production under, say, Docker or a traditional process manager.

I can of course work around this with a simple try/catch, but a change like this would make the library even nicer to use.

**Comment by sloria** [comment]
Thanks for the kind words.

I'm open to this suggestion. If it's the convention to pass silently, then we should probably do the same.

PR's welcome! =)

**Comment by euphoria** [comment]
I don't know whether it is convention or not, so I don't want to impose it on this library without knowing, but for what it's worth I manually use
```
try:
    env.read_env(recurse=True)
except IOError:
    pass
```
myself as well.
