### ISSUE TITLE
The fix provided by #96 does not work

### ISSUE THREAD

**Issue by ribeaud** [sloria/environs#100]
See #96.

**Comment by sloria** [comment]
Would you like to send another PR to fix the behavior youre seeing?

**Comment by ribeaud** [comment]
Yep. But this time, I am going to spend more time on it. Let me a couple of hours... Will come back to you.

**Comment by sloria** [comment]
Thanks!

**Comment by sloria** [comment]
https://github.com/sloria/environs/pull/159 has the bug fix and is released in 8.0.0
