### ISSUE TITLE
IDE autocomplete support

### ISSUE THREAD

**Issue by rugleb** [sloria/environs#103]
HI!
Thanks for the package, looks amazing, but what about IDE autocomplete / IntelliSense / hints?
The IDE (I'm using PyCharm) does not prompt existing methods of the `Env` class instance (see picture below).

![Screenshot from 2019-09-20 11-15-20](https://user-images.githubusercontent.com/26823697/65311230-9dc5ab00-db98-11e9-9c5d-1bc372f71db6.png)

For me, this is an important drawback of this package.
Will it be decided?
Thanks!

**Comment by sloria** [comment]
This should be possible with a bit of code reorganization. I'll look into it when I have some time.

**Comment by rugleb** [comment]
@sloria 
Super! I'm waiting.

**Comment by sloria** [comment]
This should be implemented in 6.0.0. Please give it a try!

**Comment by btx** [comment]
It works, thanks. I had to annotate the type explicitly.

```python
env = Env()  # type: Env
```
