### ISSUE TITLE
dump() is lazy?

### ISSUE THREAD

**Issue by jacopsd** [sloria/environs#106]
```
> from environs import Env
> env = Env()
> env.read_env()
> loaded_env = env.dump()
> 
> loaded_env
> {}
> 
> mytest = env('MYVAR')
> loaded_env = env.dump()
> loaded_env
> {'MYVAR': my value}
> 
```

So loaded_env remains empty, even if there are valid entries in .env
After a variable is accessed via env('MYVAR), it appears in the dump() result...

Why not in the first case?

**Comment by sloria** [comment]
This is expected behavior. environs builds an internal schema as parser methods are called. Otherwise, how would environs know what field types to use for each environment variable?

**Comment by jacopsd** [comment]
Then how can I get a list or dict of all variables read from the .env file?

**Comment by sloria** [comment]
`env.read_env()` parses the `.env` file and adds the items to `os.environ`. From there you need to call the parser methods, e.g. `env.str('SOMETHING')`, then call `env.dump()` last.

**Comment by jacopsd** [comment]
I understand. But I want to get a list or dict of all variables read form the .env file. Seems 'dump" does not provide this functionality. So how can this be done? I cannot do env.str('SOMETHING') since I do not know upfront which variables are in this file, so I do not know what is 'SOMETHING' ....

Thank you for your help

**Comment by jacopsd** [comment]
In dotenv.main, I found dotenv_values() which seems to serve the need
