### ISSUE TITLE
Multiline values question

### ISSUE THREAD

**Issue by webknjaz** [sloria/environs#109]
Hello,

I haven't noticed any explicit mentions of it but does environs support multiline values for env vars in `.env`?
For envparse, for example, I had to do nasty tricks to make it work (like use `env_var='many\nlines\nconnected\nwith\nexplicit\nline\nseparator'`) which may be PITA if there's a lot of lines and/or special chars.

**Comment by sloria** [comment]
environs uses python-dotenv to parse `.env` files, so your best bet is to look there.
