### ISSUE TITLE
Exposing derived settings via Env() Objects.

### ISSUE THREAD

**Issue by gk-patel** [sloria/environs#135]
Hi, 

I would like to know if it is possible to add new varaibles to the Env() object after reading the file. 

For example, lets say I have the screen HEIGHT and WIDTH and RESOLUTION = HEIGHT * WIDTH. This is a simple example, but there could also be cases where the output from some function could be assigned. 

Now in the code, I can access env("RESOLUTION") instead of having to do the multiplication again and again. 

Thanks for the great library and for considering my request.

**Comment by sloria** [comment]
I recommend using a settings module or object, e.g. `settings.py` with the parsed variables as members.

```python
# settings.py
from environs import Env

env = Env()

RESOLUTION = env.int("HEIGHT") * env.int("WIDTH")
```

Your app code would then use `settings.RESOLUTION`.

This has the added benefit of parsing the environment variables once, when the settings module imported.

**Comment by gk-patel** [comment]
Ideally, I would prefer to access everything via the env object.

**Comment by sloria** [comment]
Accessing `env(...)` in app code is not recommended and therefore not treated as a first-class use case. Besides the reasons mentioned above, it is also prone to programmer error/typos (e.g. nothing preventing you from doing `env("RESOLUTIN")`).
