### ISSUE TITLE
Possibility to disable proxied variables

### ISSUE THREAD

**Issue by chris922** [sloria/environs#144]
First of all: thanks for the library! Makes env-handling much easier :) 

Nevertheless I am facing an issue with proxied variables, we want to allow env-vars having a content like `{{EXAMPLE}}`, but unfortunately environs tries then to get the content of an env-var `EXAMPLE`.

I found this described in the documentation as "Proxied variables" and also took a look at the code, unfortunately it is not possible to disable this and that means for us we have to switch for these env-vars back to good-old-`os.environs`.

If it is fine for you I can try to create a small PR, I would propose the following two solutions:
1. Global setting, e. g. provide a property `proxy_variables` in the `Env()` that is by default true and could be set to false
2. Named argument `proxy_variable` when getting an env, e. g. `env("SMTP_LOGIN", proxy_variable=False)` (of course by-default also true)

**Comment by sloria** [comment]
I recommend upgrading to environs 9.0.0, which removes variable proxying in favor of [variable expansion](https://github.com/sloria/environs#variable-expansion) (which is itself opt-in).
