### ISSUE TITLE
recursion happens in dotenv even if disabled in environs

### ISSUE THREAD

**Issue by rptaylor** [sloria/environs#200]
Similar to #199 
The way that read_env calls load_dotenv
https://github.com/sloria/environs/blob/master/environs/__init__.py#L354
https://github.com/theskumar/python-dotenv/blob/master/src/dotenv/main.py#L306
IIUC it looks like you get mandatory recursion behaviour via the find_dotenv function, which can not be disabled.

This could be very unexpected for a user specifying recurse=False in environs. Preferably recursion behaviour would only happen in one place, and it could be disabled too so this depends on the upstream dotenv too.

(Personally I would want to always disable recursion in production, so that app behaviour is explicit and clearly defined, with no guessing about where to get config or the possibility of unexpected .env files accidentally picked up from other locations).

**Comment by rptaylor** [comment]
Nevermind, dotenv should only do recursion if the path is None but environs should be calling it with a defined path.

**Comment by sloria** [comment]
Can you repro this?

If I'm understanding the code correctly, we're never passing `None` to the `dotenv_path` argument of `load_dotenv`, so `recurse=False` should behave correctly. We also have a test for this: https://github.com/sloria/environs/blob/a483993ce2cef9b45ad399f794ef3424e73fb431/tests/test_environs.py#L260-L265
