### ISSUE TITLE
Dict Error -> ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by gdjohn4s** [sloria/environs#202]
Hi Sloria,
i found this error while running a script i made: 
>   test = env.dict("id_services")
  File "/home/john4s/Desktop/pyMail/.env/lib/python3.8/site-packages/environs/__init__.py", line 89, in method
    value = preprocess(value, subcast=subcast, **kwargs)
  File "/home/john4s/Desktop/pyMail/.env/lib/python3.8/site-packages/environs/__init__.py", line 174, in _preprocess_dict
    return {
  File "/home/john4s/Desktop/pyMail/.env/lib/python3.8/site-packages/environs/__init__.py", line 178, in <dictcomp>
    for key, val in (item.split("=", 1) for item in value.split(",") if value)
ValueError: not enough values to unpack (expected 2, got 1)

This error appears only if i want to get a dict from an env file, i tried to pass 2 args in the function but the error appear again.

Regards,
john4s

**Comment by sloria** [comment]
What is a value of `id_services` that reproduces the error?

**Comment by gdjohn4s** [comment]
id_services value is:

> d_services = {'google': '1', 'outlook': '2', 'libero': '3'}

**Comment by sloria** [comment]
What is the raw value of the envvar?

**Comment by gdjohn4s** [comment]
Hi,
Env raw value Is:

> env = Env()

**Comment by sloria** [comment]
I meant: what is the value of the environment variable you're parsing (`id_services`)?

**Comment by gdjohn4s** [comment]
Sorry,
Yes, the variable Is > id_services

**Comment by sloria** [comment]
Right, but what's the value of the variable?

**Comment by sloria** [comment]
Closing this for now. My guess is that the actual value of `id_services` is actually invalid. 

Comment here if this is still an issue and I can reopen it.
