### ISSUE TITLE
Does this work with virtualenv?

### ISSUE THREAD

**Issue by callum-tait-pbx** [sloria/environs#210]
I'm trying the most basic setup possible and I can't dump any envs?

**Python Version** 3.9.2
**Environment** Running my app in venv, `.act.secrets` file is in the same directory as my python file

```
# .act.secrets
INPUT_TOKEN="alphanumericstring"
INPUT_TARGET_WORKFLOW="workflow one"
GITHUB_REPOSITORY="owner/repo_name"
```

```python
from environs import Env

def main():
    env = Env()
    env.read_env(".act.secrets", recurse=False, verbose=True)
    print(env.dump())

if __name__ == "__main__":
    main()
```

**Printed Output**
`{}`

**Comment by sloria** [comment]
`virtualenv` isn't related to your issue.

`env.dump()` will only dump variables that are explicitly parsed, e.g. with `env.str(...)`, `env.bool(...)` etc. This is to prevent leaking unwanted variables.
