### ISSUE TITLE
a list-type environment variable contains tuple-type elements

### ISSUE THREAD

**Issue by uraphaelp** [sloria/environs#216]
I have an environment variable called "SENTINEL_LIST", which I define it as
```
➜  [15:31] ~ export SENTINEL_LIST="(127.0.0.1,26380):(127.0.0.1,26379):(127.0.0.1,26381)"
➜  [15:35] ~ echo $SENTINEL_LIST
(127.0.0.1,26380):(127.0.0.1,26379):(127.0.0.1,26381)
```
Here in my code I acquire the value as below:
```
SENTINEL_LIST = env.list('SENTINEL_LIST', subcast=tuple)
```
I hope the type of  `SENTINEL_LIST` value would be `List[Tuple[str, int]]`. Result turns out to that a list containing three string-type elements:
```
["(127.0.0.1, 26379)", "(127.0.0.1, 26380)", "(127.0.0.1, 26381)"]
```
I wonder if there is a way I can acquire the  data type as `List[Tuple[str, int]]` instead of `List[str]`? Seems parameter `kwargs` does not support this.

**Comment by tombreit** [comment]
Perhaps related: I'm trying to store the Django ``ADMINS`` [[1](https://docs.djangoproject.com/en/3.2/ref/settings/#admins)] setting via environs and did not manage to find a representation of the desired setting (a list of two-tuples): 

```
[('John', 'john@example.com'), ('Mary', 'mary@example.com')]
````
What I've tried: 

```
# .env
ADMINS="(Doe,doe@fqdn),(Joe,joe@fqdn)"
```
...but this translates to 

```
 ['(Doe', 'doe@fqdn)', '(Joe', 'joe@fqdn)']
```

[1] https://docs.djangoproject.com/en/3.2/ref/settings/#admins

**Comment by kethan1** [comment]
This is a workaround: 
```
import ast

env = Env()
env.read_env()

print(ast.literal_eval(f"[{env.str('SOME_CONFIG_LIST')}]"))
```

**Comment by sloria** [comment]
closing this, since https://github.com/sloria/environs/pull/241 provides a solution
