### ISSUE TITLE
dj-database-url is Out of date

### ISSUE THREAD

**Issue by 1oglop1** [sloria/environs#226]
Hi, I'm using django-environ at the moment and this looked like a good replacement until I read the dependencies.

The reason I searched was that many django projects reading environment variables are not maintained or did not release the changes.

`dj_database_url` is version 0.5 and renders wrong db engine. `postgresql_psycopg2` jacobian/dj-database-url#131 - which according to comments had been fixed in the master but not released.

I abandoned `dj_database_url` for `django-environ` which I found out suffering from the same problem (not releasing) joke2k/django-environ#282

Would you consider abandoning or vendoring dj-database-url?

**Comment by sloria** [comment]
I'd rather not vendor dj-database-url. For now, I recommend it through git, pinning to a commit that includes the relevant fix.
