### ISSUE TITLE
path parser rejects Path defaults

### ISSUE THREAD

**Issue by timnyborg** [sloria/environs#228]
When using env.path to parse a variable, you cannot set the default to a Path variable:
```python
BASE_DIR: Path = Path(__file__).resolve().parent.parent
MEDIA_ROOT: Path = env.path('MEDIA_ROOT', default=BASE_DIR / 'media')

> environs.EnvValidationError: Environment variable "MEDIA_ROOT" invalid: Not a valid string.
```

Instead you must first cast it back to str:
```python
BASE_DIR: Path = Path(__file__).resolve().parent.parent
MEDIA_ROOT: Path = env.path('MEDIA_ROOT', default=str(BASE_DIR / 'media'))
```

I think this is a bit counterintuitive, and it works contrary to other parsers like env.dict, which will accept a dict as a default, rather than requiring the string representation of a dict.  Happy to try my hand at a preprocess function if it'd be acceptable.

**Comment by sloria** [comment]
Closed by https://github.com/sloria/environs/pull/231
