### ISSUE TITLE
errors with raise statements and basestring.... not python3 compatable?

### ISSUE THREAD

**Issue by tuxpowered** [sloria/environs#293]
I wanted to try your tool, as it would solve some issues, but it appears that it is not python3 compatible.?

**Comment by sloria** [comment]
environs *only* [supports python 3](https://github.com/sloria/environs/blob/e36f11405339cdef7bee8f23de9fa5776a3aad4f/setup.py#L57-L61). what error are you seeing?

**Comment by sloria** [comment]
closing for now; feel free to comment if you're still seeing issues on python 3
