### ISSUE TITLE
fail if specified .env file does not exist

### ISSUE THREAD

**Issue by rptaylor** [sloria/environs#294]
Previously discussed in https://github.com/sloria/environs/issues/199

See https://github.com/theskumar/python-dotenv/issues/297

It looks like now there is https://github.com/theskumar/python-dotenv/pull/388/files which will cause load_dotenv to return false if no vars were read:
```
import dotenv
a=dotenv.load_dotenv('no.env', verbose=True)
print(a)
False
```

So for the reasons previously described it would be good to have a way in environs to force a failure if the specified env file does not exist, by e.g. checking the return code from dotenv and raising an exception if it is false.

**Comment by sloria** [comment]
#311 modifies `env.read_env` to return `False` if the file is not found. This allows users to handle that case as they see fit, e.g. raise an exception, log a warning.

Closing this for now. Thanks for the suggestion!

**Comment by rptaylor** [comment]
Great , thanks @sloria  !
