### ISSUE TITLE
Incomplete Typing on Env methods

### ISSUE THREAD

**Issue by aThorp96** [sloria/environs#330]
Hello! I'm having an issue using this library with in a project with strict typing using pyright. The issue I'm experiencing is that `_field2method` returns a `typing.Callable`, but the args and return of the `typing.Callable` is undefined, leading to Pyright identifying that the return type, and therefore `Env().list`, `Env().bool`, etc, having the type`(...) -> Unknown`. I recognize that this isn't an easy problem to solve, but I wanted to flag the error and mention that it may be incorrect to include `py.typed`

It's incomplete because it doesn't support imports such as marshmallow, but the issue can be seen on line 367 in the code in the [Pyright AST viewer](https://zzzen.github.io/pyright-ast-viewer/#code/JYWwDg9gTgLgBAYwgG2QUwTYEB2BnAKFElkVxjQA8ZlgAjI8aeAMwFcdMIVDjm5g+MBhiMS8AFZ5ccAIZ44YAJ5TcY-sggBzLYK3rSEXk1JQ0B+DCVg9BFlAggyqEdnwA6WXQQCT8ALKyYDY4+vaOcGg4bE58pACi0SB2Dk5gsjAAFrR0vuJwAAoZmSkRbFCo9O7pUHhoefxFtWgASmh4bMgwADRw5cg1dQQWcCCytZljqBAA7nIKY6VOACYQFDgAbu5jgg2kAPozssgA1vswEPsOa72assv7q+sbw-v7x8hvcAC8cADaACJEht4lAHFAAb0gZsAQBdV4AFR+cCsIS07gR1jQADVxgAKAH7BEAgCUBH2AGUYFBMcJkXhqeSAELcZC0+q-Ois4ag8GBYJ6ZGovTuflov4MqC9YWhdwAGWADIl1Nh8N50AVDKF1hFmpgyqg8IAYsA0MhlkbZFwoEptWj3ABhD5edB-dzu3pjdwsU3mvDuE1m5bwilsbzyeC-GXogCqODcf2jGKx0p1sqdqBdaDdHrgRNhntk3t9y39gfNxpL7LtIvZfy9PqDZZLlaDAHkoJbrbao2nY-HcH9y8t2b1h12Ljb4U06lB-GgshBljX0866OhhuT4gANAoAQQAcgAReJH-bYvctfb7hEI+ItA-IszuJDgYDoPEQvEAfgAPABCAAdQCSUAgASQCAG88T+PcAFoAC1ZDggAvAAGOCAE59lhABqEk8QALjgv4AD1AIAX0I2EACoSW-SjSU3BBkHkBRgXVKA8VxZA2DQTiSUIgg4BEuAAXElpZEVNBlxmTIojkHBIk2YAHBwEAongDZxmALM4GgYTROAFg5DgMwAEc2FUmTlI2VTcA0nAtJ0vTFT6fAF3cQyRPEgFmNYvB2M2HjgGWDI3E4vEOLBaBBO8uBljQEy3kEYAYDePF4tEuA6mQFhPXaPBZC0NBCJy6lejQGKoH2DTAuK9oyqTOME04vVek4sU9HhbK4uy7LcpYdwqvBWrCoahRfhG6AxvqkrCH60SOmELiSXcFL43S-Y8TqoqSrJYYWLYuBgQpNBjhkyL2U4jrNgEoTsvSQL-OOmcqodXAWFoTBIp4vj7vi3zJOk2T5KU+5lkFWREDYBkIkGKqUUyDIyBwL7gEwBbRJmNLMlMugrK6ODdgRqBRgXTIly87LfM3RLksbc0ACYNMXZZMuyxmHhmlgrUnJQyuHDsJ2gJRuni1nKYeHBZA0srJXF7KaMV0SwDMNWIAQQqmr7dw2zALBcGORNdYzVj1zQWFkQPXA0BVkS1bQDWtcC-YTiOKAtH2GW6p1+0zssqItYNK2ozYMAPxJcWSTgOCAD5CnGWd5zZh7RPp8m2Y5xacrNFgyuhDZISy0SfdK8qpRLkT6dkToYD9kU9xwHtRiLEBFTwPR7f6jpwwZBvZX1w2ZeQP5Qz7mBQ7gG2cDtqu4GV+eAGI4HHup4AgEyzHQbSnNbiYpk0GYAxLOB3fGLQscWu4HhruuB-RJuW69dvAq7+ftNoMKKAfvWDbcY289srNQHDgP4QCc5JjNlmP4Jt7RPwLCiXWCDu4536kmAAkhQKAMCoFrldHAxuzdEFJgQQWCBIkeo5ynjPOeaCLJWTMMsMqXIUDIktMgOoqDRIfFmN7W2v8h4ANHqw5ANDbbcJEtNGqu0JqCP-kbUeSYjwY31ArCuqprYSPnqze4GRZDyOHsbJMXVQgGlTPA4h4jZ6SIXjRc+ns8DdxjvHJB9ohGKL+PmNOi1jK5zyutOoF1mEULMlJOoJ1NhnWCZFUJNNgRwGRgoY4Zh7i2joGgBSQT0DLHcNPNAcxP58QUAgWQOAcBrDgBkxQScZLuD8mg3q88uZuw9pfZEkNMDZ0aXAT+oUMhoG+H07+dCelmTQJZayyxvgMKmbY7KvCZj8Nnt8RZyzRk9Jvo8JKtcujfC2XfLo+kyaHJ6KE6Rs09rtG+Bc2R815miV0d-WQ3wnn6NsWSNBjtnaFVaRfSacBIKhLLmVBxl9qgQDAHiMuMcWDQDgGXAQSlvkOBdngP5ntvay3aAIEyiLdhgqvv1Ci88-GKkEAyMpWs8QtJ5nzUWFi0AxzKcuDuYYjqBW6Y02lNVebdkLMWJsJ8gzzz6mMrmyIeX7D5fzPENEaItMJb0eVhLPk5zNHUHxjSEYPF7qUrUvxaqyBOGgfYeqIzSpLHic1DI1U9Ilb8KVMrRbWvZRGb4OqzVuoZMqhVJYMWXztf1T1Jqxa9OOHxXoGtKCmgeKG+ked1olXSuEEA+woh2TUlytBZdehc3cAcnZddRXz0GutLmeA-ghrQEoKeXNS0QHKFrN2NbkTRtjS2208Lq1KFJSZIp9Q3Ivw7noLVaC-FlvOiVKAY6xk4OkpEkE1Vs1jM5gAcmBPZdSmlw1QF0hbMSkF20yU7ccmpzQ401oogCBFlT15rriaJINaCNWlUfSJMt6bqqVp7bCTwwQojs0Lluxyzk916QqfAde9Tn1zoXOUJStD57UgFqEvxKLNba3feG3iHJFDq1RYVPEA7fUYbRQGvAsHFoDslSWdwiVZy6VoChNAxGI1MvnlQLWBtW7uBCt-CK1V5iRGqrO3xJlJ0NRndh+dETgT8fCrgWJq60EsA3SpNSoHd37vQIe6QTbTWhuvUi4ZZVILSM8I4v4aFYQUTXQ8npFm7ntAc-1WFqQRPglCZ+6RP7amXtrcNaggG8ROfGvNKjkROFvtXZ+gdfmL2dqngO+eZgYAIZw3xYY2VJZUzeGXL4vxcvS2xfFNLGXit0ySnmdgnAWYUyXDSjgCBf7QItgVNmWK5YVxcQnN6c4GshOyhnYrK6P15wLsCYuObsXywqvPU5v8n7ImHW-UItiVVtKcfFXrbiRQeJHl4hEsIxO4v8UNM150cmneyrJ+op0ruXWXdhwuiT5ByGQKk5Y6TMlKWyXU-JhT2MlLKZBqp9QdX1NCZFntvQcFLJI-hiAMaT3xt+J+5N0rUjpo07gaF2LeinMi5+itVb-NJZW0WCtwrzR4mJ42qAza0dI5RwFs9Pa+1hIR+xgQCw24jtCDdoyEnE1TqqkLxad3F3KZU4tNTm7NM7u0uBg9AIj0OFZ6e7t5OjM3rB-e7DkXsqvolz3RNX7wQJbqAFv9QRhA4CAwrhySuXIHv155JisuRLlagIh22nP4f7Bo-CwPNHvi-HEqbsPXOg-sc49FqPPPfhIbQShxPuHJXNc-LIbnuHfWqs45Qbj8Aop3WqgKhTw8BLCekab5zAKxuNLC3Ndo2GyWd3wDAKlrHpEV+OP0qv1Ujfqui-8Cz-zrOqmh2hkXASxfSa92Ehd8n+8CaU89xf66nfbr3srnT9Q1f6cZ4Zq9N7BCmcBePqzNm7OubQfXu-T64Cps8wZWL5vfNk8S6Gv9VB1js3r0ixN283N3iy-2twp1+BS3oXg190y3MAlkG3Wi61NX2BW0GxQLK1gKUkq2GAziNRNS9QnktSDC5RtXrj20HgUUO3Hn1UnmjljgTiTDrAbBLGbCDBO3inbwpS704FY3IMZWZQdxym9XgF2C9ApAQHki9ARAAE0Ch4h9h-A9wCgCgMEDwABxU7QQWeXlU+IrIsSQ6QosOQhQpQlQtQzQiUUQqhKRWgEyclTvbvV1CeQQxSVlQKdlAKPAFwuggVanYcMVXxcpKqEg80ekUQ+KM0PxUpTMC2XwiMOKeeDlBQWgiMYcHaKnNgmnZYIIxpfAhjKqJjYAFja1POXoRHGif5fPLbPI1dWrHwXse0OgvEPBOI10d0dwXofMXocg4fSXbA5-LPAdA6cdEIvQoMZENIhkYcKIhPUlcYsI5cAwwVP0HIrA9LOAnQ0I+tPA6rAg01WgBkJYuVXo0QwxYROBS2Go-5XbVgoVPULVbYiY8Iw1MYQg8gk4vojYirLIh4xUGAPEZ4pYm4xxA6AgfAsjX5I4wE+KAdX+FqQcdRTBbBLMRBZWBKaI9ubBObMmCPboSEOxQlAgXbFEqqLMJ4kyL0NgLAThdwRUfYNKcki2fYAmdKSDM1akPQNjXDGOeFGjNyWhU7H3JSaA0SEUyg9EFo9REY9wPACONKPERKWgbEqqGOPxGjf8CPG9V9f4eEPY5KKE12TpWE7KeEyU9wREsBZE3WUxLQchJWbuT40NPAC4zxaYyeLRGxeKT4+LN0mgmwr0jZTElUpkmdCuZESEabUSTbaokkxgi0u0yk3nHg5wxHO0uo8UwYsUj9UQztdFVMvgsqe4tY4cZEA4ogugr4vMl0giWMsEn0vM+LRkpwos3jAI-QvMd401T4rmBI44+LAieeesy+HbbLLMzYpSIFNBZ0mtAs1srWejdoIo-vUo0JUNOUrkqFSLQSEQ4g5swsxcwo8DZjVjT+TcvdbcyLOFMmUNCo44JFOAIEigEAOUhUwEgEb4QkgARlhXhSZNiFFPYzfNoEBOVNADDPVP7XYyDRJQNLzCNPRVUBwB5L4gRNAXMUTLty7gtL1HRPsVqK1TT050cMpT4NQrth61NwlOUGQoLQgHuB8JGPj24IXLPPY0J1UT5LJlIt4OpURxhO4vgN52ngEVCQlJzP6mANXSly9Er0E3BAJBtmci-jgAACkKQ2wDwYMoii8nZ4BaLpAcB3ANKtKjwMAlx+IhN3ta9Utwl6g5LV9FMcBIoARlKcNQp1LNLtLSRn8PNpFNx9hEgYgkQmjawsRcQuJCRgqQBiReguQOBpkYrwT8CogYh9hSYKLGVf46wgqkhjtehgAtAKkzB9h9Vy5RF2Fjg6hds8qQqnjNhV900i9Kc+MnLB9FKWA3LKloZhk4A11IJUQ0BkCCt9g7NlIYgdKuC8VKkiqSrTVyrTtiKZLBihq-gB1bCpK9KeMABpGtTiGvUTcS+ykzJqrjPyiIAK+KG8iatNAUpSIa7QkyNKu64CsueimYKqOnH4KA4Co+L6zMgYyc262PXDcc73E68-M6ovKrZKZYCQR4OgfYfoDK2pLic09REcyjBMk0oim0bQvwBKBG55OgeQU1foXS4vOADBPwA6myo6+hE6loDgLADSGXHpAEBEeSImxG5Gioc9WccZSZMwBQLIeoeGuCEmsmuCfoGpBAE4BqPJBpMZAEWQxtRAMpJFSlVAAQeAHGLIMqGwMALWrvHWiWqWuoGWioZWxadzS66qeKZanOCU+Gx4fRUmuoPm5AaoWpLKok2oym-Sk6ba4eQ68EYUk6xyr+Zy1y9y3q1fBKd2smuAGMFoOUGDC6pwK6iE-Y12tAHYT4FGzKjGiqf224nG1RPG1DcdQmvOgur2wOnjGm8QOmhQWyxmhdZmpyUAKyxS0JTm7muuqSQu-m0mIWxhHFMWomuCfO4eq25AOWhWkqJW-utWtgDWpSVMnWtKOAfWzIQ24AY2reheiW2e98eem2tzTO1-KAR2-G1LQYoe98L2n25oP2rGoNLjIO+IEOtwMO6ACOhdKOgfBS6AJSnqjy5cM+he1O9O3yl-bOgohG0pKQ8mioVG5odG9jXE0EwNCuzAKugm-IeGspLQS4FB+SBu43EO6m2m6ytuhm52pmlmnu9mxpAe8W5Bq0Sh2Wse2ZEWpGTh0hiAOCChtAeexexWsSVe9W0pTepw7evW3GA+o+hRk+iQYR0R7h8R-oS+3qa+gK4Be+mA4Gkh0Ich7Rl+hGd+gi24xu+AH+4vP++m8O5eIm4Rsqyx2WsYW0KXRx-StwAkOME4CpGYJSUm+WwDToz3HOFeD9CAPoCJLIFGaRcmFvR8qe4ZZym+uyoBoseS9fRSq-S+SfO2rOh2w6bwlOtOjIks0sS0tOvI-AxjVc-g8o+AsqN6NoDoLoZVaosusEhMyUYU7M4C5NfoOncGuAFeNsDYEaUKcW5ck8ko+oHBMWsmZJpSbZFp088HUpWGeoT6hFTJZYeKFeC4DWnW-oBGBeWQFgbBGiSB7JpJfSBABAcoJheKDOY84otcmc8oj+bBiuWxDIakf042SUaxYM4bfRcFpRW07C0IKFjbWxxxZxBMrp9oe+B+yMEQlaOnJcnZlZv20FqUROrvXByjHFjLa532tLcElIxOLIWpv4tYqkKAJp3OpZ35tpvKe8vPW5tFgZvB1xIoA2kijvMi-ijiplzIQG-qCSuPExiI-FtabZlc089+-pj+6luAsVzIT8BcBlqpuUbQOUNAOZ5AFl1Y+pjBJyTlhmaAMYdkmIMovl+A3bQQeuZDYxuDYG5aAG8tJ1jIb2V15il9GhvEa6cvOAP6Xu2Kf+hfMZaPAddwcOVVmfN7IqGAakPETQHQHCkY9wlMtivEZNUlvN7QXQdbD1wq+103W7QY8tnNrifN6trQflvifoqLTVGTSO-J9q0BqKuOyBuAfNsdi1s0DOhBipggRl4ELVXyJuWyEDF3FXXTL7KqepcSKZt4WIz4fYTptGlOKWcsrmerLOOp9g80KEPdj4N4JiLgveQ1c90bK99wO1noMSL1mJkSSql9ksC9qWTIm1-0FkFAKEURX9iMgDoMIDxrd99lqESUaDr6Bi3FpY+DgA1l+po0O4L9gENDjIaDxKBAUAB82D5mN9nD-0cysjqYKEUj8j5AaDmEs9wD0beeCsmEkE+eAEGE6MxaRC74DKgjTDV2GE2xRCgNFAvAb4AkcgwkgEcC1UiEKOMc4bVRdjuDzj+-Gj9wFRTAWxZT1RQT4NMTtFET6Tk0qTiz35MFWT+T-uxT1zAEWcpQPAMztBNzmsmtLznOHz-c4HfzxaZTrEsMkLuAdTppbKZC7TqjwbEDjsoMKEZCwk4T0Tp2QjV2ZCoNEZVmvDTD6j0DgzgZBEHuxjgZArkjgZeL5YLDpL7Io8AZSrigaDgrurhr998rjSKEaroNdILITr0bfV4cKEQbzIVj7QfYHeM0YbxL01rQc1y1sbsSfNmbydljoNAr5Urveby9-TnrtAcyroWQPrnu3b2QaDtgKyZYmrDjxL99mMGMDBI8KEG70Ka7-myj+r0bWB1bgEXRz+pIM95rBrnHdK0mKEF6kj4mpG2Wl9sH0bR4OHr2jB2cRj1HoHr5hG6Br20HurZHp+kez4KHsSYnr22Hzx1B-HxHwnxLlH6nnh9Bsn5Trhmn7Hr5-YlstKDKQaZVSqKTMqfYcDtkLEZEBEKASNSISgdIB3WPWoYX0X6sX4DhGq07STadZEefUtc3f7ZhKpVkKq6LXXufWXllBXgFKgOXh4ZXIlAac3CtX+Qz-USkakUcC0q0+sfT1boazRX4SCElf5gJUG4pZ31RLxdlj30hYhZEQP03i7XzMqTqRFrQZEJAFwTANwf0U5E0vNgE4nc3R2H0SgOFyP93rEKFhP5A95uGNNUmdFQ9i0l38vmkFMROTBk9pcKeePrn5KK4LLvnvOWqqPrEEZ4Grq38SCT9Mq7wt4Ea7FN4CiULKTb4af0XKTCiSqc3+Xu3tfydHf23pOCiEkOOG9aZ29cyAxE6AAVjQm-KmYAAFKUsAEBKthtqsvsccNhG8Juy+3e2+wgZFg-XebNAlerIFXnAEl6RoP4VULkJqjzDK9xeqvaqtC1EgQA5mYIBZuAJQCQC1ewZWqkgOECnYgY50ZcNDGGibBn874QdE5ASZGBKBmaXAF5HngYITIjAkSmDjhSJUMmg9ayN2GvpyQMYeMLIEOkGwiV92MkWxFPVOTg5kYdkf8qLQSZmBQBEScOIIwSj8D+YKIMwPUBYYL0KBGaZpDQJErcCHceSNgXACUDq1Vgt6JRngBEHKCMA5QNQcbSnrUhMkvQawevR8Y1JnoaCfAcJmhh1AkAwhSAJ3CMQGDPYMQTSNTAC47tx0JkCbiJSFKhIV4TIW0Kcl6Jd5SAQSRnHjBfxT0ioGkTQSoO0GiCFADRUOm5EkGnNV0oAswE5CxzYpkQFKYQJgBfAfNNI9gbFJM1XQxEuhTQnoSUMFJiVF8UuLugV1cofROgy4MHMmhhhggd0+7Pytih0r1EcEJQ34A0M0jNCNI3oVklaBOChI2IVUVgJsMHQKAwcKeMZJIJqiQw8SsrGlBcIOFIBEoL4S4D6HQAwpX6sQkWigDmZ9CxklKUgNsI+ChEHhcAAAPRiRGBejUSNJTGR+J9WeICbmtAZIPC6cDbcUidTjauVkhIAWGPAGqTQwvhUQAnHYNMgPCRAosdYcCJyG4sURaIgPM4LAHeYGRjwVSJVE2AoFkQDAibiBUVIgiYA3bPxPrg5EPCyoF-NsDgGQC2hSRNAxFEcAUC6A5mOAbDMKM5GPCGByaBADMHZjdsbqDw-FFsyOCnBzglwa4ICU1EPD5WaCVBvLVRpDdfgKI40dihjgwiM0mBRfDEXkiOiBRVAAEj4TtF+sMsByNYBmjxAOizgE3ConAKMCDJMB8AyihgPmaJRvgqYrAYlG7YSl8B8eXtitWBrhjng1qXNsKKji9J4xdQIZFWJTGYC906YzMQ2I4zxRH+oQigNQByAfCnIf+MYDLGnR998MSUYAJQBkhut8oQ4kvsL1H7CBSSusLBOSUnCAgpsnBbzuJA+g9jqArcfsYjBuqDBBQGaO3rvVximRXwIAGQMXxHHbt4RIkJ2j0hQAPBLxlABNCHyfGZsHxmXEvikLGFe5P0T4ttGYBL7nJ5ii+P8YBJHGSo1cH4p8RRHVzDjKA16UJEoFPiDRjBI8OUabhXjW9voaUOUeMnXgaC4YTCScRBJkCvgI4C4ZxsIS-rUF7eOcMCfBKDLV9PxEE34NBPAmUApmGcbJOOPla+RK8EOfzPAWSRhCzAao+ALPCBy4ZKhHmDJFDGWCJRckUzbKIRDuyukV2akf0CvmjodU388Qm8edkCSPY7u0A8wIkMMkW5oArpc5NVEuQTQOkqiccetF8zdsfM36OPkHznQnVtJIDQpmA2wxdVt8WmPfFmAUBQ0v4ZmW5OFnaDXpKotk+vNPkHFvBm21IIfu6xBR5gZxTKJar6x6QSkqhrIf0DUCwDHAnJe7IkY4HR5VRG+fwMuIgkGhAEaGe1JQK3RvrUUTqe4FtvQBpLxsuIXVdfnlAohZtb0cgLqWyXqCQQy416Mpjk0HEQwqpXEfngilmyZSK+wgPNM1laz4ImUCZVIWuIBBtBdADIRGNDEkkC1EYxWY8UNynqIoAABrdLLj3S8k90hovdNGBEiQBaAYAHMw0GCAwANJYSjdU1oZpV2u+V3OgDiGhcEhOcPxEkgrZLSYU7UhdP1g3HowfoG+L3IFKoEpIyBtoF5tDEul71lpJQgalNLXR5IYwESaGJDBYAsAqoO6d6gZJi70TzcZVCqfXzRo1S6pBPBAA1waIdYpYKBb4DCl1Z+5Z4XE6rKTGlT+Tg+E4jKQAPZA7YEybRc2AQhVlokLEIoNrOgFXH6S6O0ADIPCmSbwAzAR07BMkmOZzAx6hMk8TdJaH3THpt0yGf1C5qLMkAazGyFUL-qEitQKgr6T9Knp-SAZNGIGUpBBmK4wZ67Yanxx3YLZqspHA2ZOCaycAtp7RHaa4nVkWxTcZaeaZlVzRDFOAOYwYg0WUkTkMsCctZgZDmkKSFpWOSqX2QT69B5ZWUvNP6hYjqTmCWIb3iV2HCbU+JEkNAGbJOmWzzpZMG2UNzukPTsU902xKqIUgEyk4kwRZHAHunDgnpMcgyTP1r4XAOZmDLmdiinhFdEuLSduQLKXBCyRZg45YDEChQNTlZCLAUGYgVnt8Y+taEgeJCPA3zzpUDXHDvjAz74lBVI1RAAhtD6QJMxAXTM8jcSt40E0KGIBklqDFtJQegSjM7JpjQzFoeAVBmMFapGFZ63obHHnxJxsECIkWCUlguML0Yb5ZUwchLOSiY5U03-LdI3iWmhppxa0yiotgtJPwBeLOWNDgLF50gUBJvfRhnN1gIhw4roZ+etO4XNxNZVBSIa33ZCqh35AIPcG80KimQQ5HmBgeHOYFwAAAEiynQAKBj0y4EKRbG2wvp3A6IVeP4ARAFB9gcoNsBoXUJr9IIyhDBHKA0IxgDwTilxeoQogUQWBaCNoJOQtnpYKJT5Q8eME7TciNgyuUPpRTMWdo1oUA7mvdJiU1RQ090+eDjB1rVIaZdMxoecIiBT0no1uM+K2j3Ea5Y02mUKXkhSWho8l74BetUloRnYp6WS3nDgDXQGValdSUuSJFdkrzbpZit6V9GKgiUVBLg76WaFtAVKbIfiaGNGltCaAIAJwdQW5H4YyRkMCTBYSso1y2gM0VSpQGgtEi0wX0PI5nBjgXCdo8Qd5fSNiRYmUAPUAy3IoCwzxsT-Qei4ysmlCzXKa0hOItF0Eiywz5AFbRHG5y3KkhTc1vC3s6ykIviho8K3fknGLZBVdwh4E8GeAvBXgbwd4B8NsAyBSEKKoo56ofyNQwApCUoleEaE6AL1EVeMVFUf0QVwQco7QpjBrQiQmonYmJXmMWkXxNKa07CwAXhhZVUqpCNihwOHGDGT4NRYYdFFwqTAHZjY0iy2Nr0pVMrpVjaMAHKu-KbV+hEmRVdsgFVHI3I1wn8Zvn5W7JcWvcJVSCv1BMxqI2GaIiZEbyrow8vwU5IblpVnYjm8gvQZUqyEJRcAfSxJoOhNmsjO4lrXtNauriOrWqr8DvPoHGGDEPVYyO8thgd4h8GF2OX5aiPeVxKbVdcKNO8u+CmSSQfwA1Y-iE5Fqs1i+bthKryFIr0couSlUeJZR5gdw+4Y8KeHPCXhrwe4W8PeG0otqDW4bJEe6tdWUrx10OP1f4DriH1dM-5B6n-lbjUrmVHa9Feyo0JRBySC9cqrHBLVHJNADIGTIMR8zbragAKjYMWsnU9IV4bQc8T9PaClJhAy4MCJmwP429LexbCEOBDPxAVcM2IkSCm2ArqxWI1KADWBCU6wayFgxL0Y8sRxIYkpEqu3uOKjQ64gVHrcfpGQMmOw71wo5EGhGaTwomVj5TFb2pxUDr8Vw6wldpR9AO4wyZKuFYCufgkrMgOq8OHiF-LnIeRsggwpuu41QomY5K2yKattXfjZ4oGiTYJt4zJrbAq6REbLi9Hya1Njqv4M6qtgX8uSTgNdMRDXTX0fVq6fYPEqSXdFkVSaO5YwoLVIacNGms1V+zMUVqpeHGI1RJoFJ85tgAuLQLJporYaw0XoxHPZrjV+s4AuEX6rhirRiTOS4weAMWU42bl4tdOK2LhE81KsxkhGuLaCI3VSqQsCG+AJFvgIxaLWOW+uPqRMYZZYc4yL9qFroV5hMcoaTDactFUe8MSjgXnk+IEV4DUBI-DhePwywMSvx6W+NBOiL4cTi2YOTrelH-G6lQ0QAA)

**Comment by sloria** [comment]
this is a known issue, and there was some investigation in https://github.com/sloria/environs/issues/120 . ultimately, we didn't arrive on good solution there. still open to ideas if we can preserve both conciseness and type correctness, but it turns out to be less straightforward than you think.

closing this for now; any further discussion should happen on #120
