### ISSUE TITLE
Default None breaks dict parser

### ISSUE THREAD

**Issue by BroFromSpace** [sloria/environs#357]
I wonder if the dictionary parser is supposed to break when setting `default=None`?
```py
from environs import Env

env = Env()
env.read_env()

my_env=env.dict('MY_ENV', subcast_keys=str, default=None)
```

**Comment by sloria** [comment]
I believe this is symptom of #270, so let's carry on discussion there. for now i think a workaround would be to do

```python
my_env = env.dict('MY_ENV', subcast_keys=str) or None
```

**Comment by BroFromSpace** [comment]
Thanks for your response.
