### ISSUE TITLE
Add support for returning the file directory of loaded env file

### ISSUE THREAD

**Issue by senese** [sloria/environs#362]
I miss the `python-dotenv.find_dotenv()` feature of returning the directory which the env file is placed.

Is there anything similar in `environs`? Are you accepting PR?

Thanks!

**Comment by sloria** [comment]
This functionality doesn't exist within environs. I'd be open to a PR that just delegates to python-dotenv. We should also probably refactor `read_env` to delegate to `find_dotenv` as well. I made an issue for that https://github.com/sloria/environs/issues/363

**Comment by senese** [comment]
I believe is not necessary to delegate to python-dotenv as it's  already loading the environment with the path that read_env is searching.

IMHO there is no right or wrong on how to implement this, just pros and cons. I notice that creating an instance of `Env()` is the main way to use `environs` (even the docs exemplifies that), so I quite not understand why `read_env` is a static method. I tried to remove @staticmethod decorator and all the tests pass. Changing to an instance method would allow read_env to store the env path in a instance variable so that it is always available for the user (instead of returning in `read_env`)

So I strongly advice to change `read_env` to a instance method in a major release (along the refactoring) as it breaks compatibility with other codes that are using the staticmethod version. 

For the PR I try to maintain the code style and not to break compatibility, just adding an optional parameter for the user to receive a boolean or string return type.

**Comment by sloria** [comment]
Thanks for looking into this @senese . I like your proposal to change `read_env` to an instance method and store the path as an attribute.

I think we can should just go ahead and make that change now, even though it is breaking. I plan to update Python version support anyway, so it's about time for a major release.

Can you please update your PR accordingly?

**Comment by senese** [comment]
Hi @sloria! Glad you like my idea.

I would suggest that we could add this feature with a minor release and work on the instance method in a next PR. I've seen on [pypistats](https://pypistats.org/packages/environs) that environs had millions of downloads last month (kudos!!) and it will be nice to add a feature to the library before a breaking change. We don't know the environment and restrictions of the users and other libraries using environs.

For this issue I fix the return type as the Union operator `|` wasn`t a thing for Python 3.8 and 3.9 versions.

**Comment by sloria** [comment]
Works for me. Thanks!

**Comment by sloria** [comment]
closed by #364
