### ISSUE TITLE
Providing millisecondes in timedelta does not work

### ISSUE THREAD

**Issue by tcleonard** [sloria/environs#372]
Providing a float amount of seconds in timedelta does not work
```python
env.timedelta("NO_VALUE", default=42.3)
```
will have a value of 42 seconds, ignoring the decimal part.

A PR to solve this was already submitted https://github.com/sloria/environs/pull/368 and closed with no valid reason

**Comment by ddelange** [comment]
could this silent downcast be a ticket for marshmallow instead of for environs @sloria?

**Comment by sloria** [comment]
@ddelange that's a good idea. would you mind reporting that?

**Comment by ddelange** [comment]
MRE:
```pycon
>>> from marshmallow import fields
>>> field = fields.TimeDelta()
>>> field.deserialize(2.9)
datetime.timedelta(seconds=2)
```

I'd like to report, but it looks like issues have been disabled: https://github.com/marshmallow-code/marshmallow/issues

**Comment by sloria** [comment]
Yeah...issues are temporarily disable as we're mitigating a spam attack

**Comment by ddelange** [comment]
I've opened https://github.com/marshmallow-code/marshmallow/pull/2654

with that, I think this issue and https://github.com/sloria/environs/pull/368 can now be closed.

**Comment by sloria** [comment]
yes this is being handled on the marshmallow side. thank you @ddelange !
