### ISSUE TITLE
Add env.secret

### ISSUE THREAD

**Issue by sloria** [sloria/environs#53]
For casting strings that shouldn't be revealed in tracebacks, etc.

See https://github.com/encode/starlette/blob/1e1f3bab464d497a9250590a72b025f6095b20a7/starlette/datastructures.py#L179

**Comment by sloria** [comment]
Hold on this until https://github.com/encode/starlette/issues/301 is resolved.

**Comment by al-the-x** [comment]
Excellent work on this lib. Seems that this issue is "resolved" in your PR encode/starlette#303

**Comment by sloria** [comment]
Thanks, I'm aware. I'll have to give this more thought. I think if we add this to environs, we'll go with the `.value` approach suggested in https://github.com/encode/starlette/issues/301.

Feedback welcome!

**Comment by sloria** [comment]
An alternative to `env.secret` would be to allow any casted value to be secret.

```python
SECRET_BOOL = env.bool('MY_PRECIOUS', secret=True)

print(SECRET_BOOL)  # => "*******"
print(SECRET_BOOL.value)  # => True
```

**Comment by ribeaud** [comment]
Related to this, it would be nice to be able to store _encrypted_ values which would then be automatically decrypted by the library when needed and up to a previously specified master password. Something similar to http://www.jasypt.org/encrypting-configuration.html in **Java**.

To be identified such values would be surrounded by `ENC(...)` for instance. As a rule of thumb passwords should never be checked-in. But with such a mechanism, this is then acceptable.

Currently I am working with a custom parser to handle such cases.

**Comment by sloria** [comment]
Encryption seems outside the scope of environs. environs is used for parsing values that are not checked into source control. If you do need encryption you can do so after parsing, e.g. 

```python
PASSWORD = encrypt(env.str('PASSWORD'))
```

**Comment by al-the-x** [comment]
Or use [a custom parser](https://github.com/sloria/environs#defining-custom-parser-behavior) that handles _your specific encryption_:

```python
@env.parser_for('encrypted')
def encrypted_value(value):
  return decrypt(value)

password = env.encrypted('PASSWORD')
```

**Comment by sloria** [comment]
A custom parser also works but doesn't allow composition.

**Comment by sloria** [comment]
Closing for lack of interest
