### ISSUE TITLE
Validation only happens one field at a time

### ISSUE THREAD

**Issue by robertlagrant** [sloria/environs#56]
Currently, with the following code:

```
from environs import Env
env = Env()
var1 = env("VAR1")
var2 = env("VAR2")
```

If both env vars are missing, environs will simply display:
```
environs.EnvError: Environment variable "VAR1" not set
```

And only when that's set will it display the second error.

It'd be great to have it validate as far as possible all the required environment variables, perhaps with a manual flagging of when to start and stop such a process:

```
from environs import Env
env = Env(eager=False)
var1 = env("VAR1")
var2 = env("VAR2")
var3 = env.int("VAR3")
env.read()

environs.EnvError: Environment variables invalid: {"VAR1": "missing", "VAR2": "missing", "VAR3": "wrong type"]. 
```

**Comment by sloria** [comment]
Interesting idea. We are already generating a marshmallow schema from all the parsed envvars, so this might be straightforward.

I'm open to this if it doesn't add too much complexity. PRs welcome.

**Comment by sloria** [comment]
I took a stab at this in #94. @robertlagrant Can you take a look at the API and let me know what you think?

**Comment by robertlagrant** [comment]
@sloria I missed this in my giant numbers of Github notifications! Apologies for the large delay. 

I was just about to fork and saw this. I've had a play and it looks great to me.
