### ISSUE TITLE
Add .url() parser

### ISSUE THREAD

**Issue by IlyaSemenov** [sloria/environs#6]
I think URLs deserve first-class handling in environs, using `urllib.parse.urlparse` as the parser and throwing the corresponding exception when the value is formatted incorrectly.

I know I can plug it in myself. But URLs are built-in Python functionality and framework-agnostic, I don't see how they are different from, say, timedeltas.

**Comment by sloria** [comment]
You make a fair case. I would certainly review and merge a PR adding a `url` parser. =)
