### ISSUE TITLE
Allow opening other files, not just .env

### ISSUE THREAD

**Issue by nvtkaszpir** [sloria/environs#66]
Currently environs read only hard-coded `.env` files, and only path is available.
Yet more and more tools allow custom .env files.

I believe environs should add parameter like `file='.env'` to be able to override defaults.

**Comment by c-w** [comment]
Note that it's already possible to read files not called `.env` when using `recurse=False`:

```py
from environs import Env

with open("test.env", "w") as fobj:
    fobj.write("A=foo\n")
    fobj.write("B=123\n")

env = Env()
env.read_env("test.env", recurse=False)

assert env("A") == "foo"
assert env.int("B") == 123
```

**Comment by nvtkaszpir** [comment]
Oh right, that's PEBKAC from my point. I was totally not seeing part of the code.

I believe this should be added to the docs as an example.

**Comment by sloria** [comment]
This is now documented here: https://github.com/sloria/environs#reading-a-specific-file
