### ISSUE TITLE
Change (or at least document) surprising behavior parsing env var when explicitly set to empty string

### ISSUE THREAD

**Issue by twosigmajab** [sloria/environs#71]
Environs users I'm supporting just hit this:

```python
➜ cat config/foo.env 
MYINT="0"
MYFLOAT="0.0"
MYBOOL="False"
MYSTR=""

➜ . config/foo.env

➜ python3
...
>>> from environs import Env
>>> env = Env()
>>> env.int("MYINT")
0
>>> env.float("MYFLOAT")
0.0
>>> env.bool("MYBOOL")
False
>>> env.str("MYSTR")
<marshmallow.missing>
```
What? Expected empty string, as explicitly set:
```python
>>> from os import environ
>>> environ["MYSTR"]
''
```
This violates reasonable assumptions that the type of the value returned by `env.foo` is always `foo`, as is otherwise consistent with `env.bool`, `env.int`, `env.float`, etc.:
```python
>>> isinstance(env.str("MYSTR"), str)
False
```
In this use case, the user should not need to know what a `marshmallow.missing` is, as it is an implementation detail, and should get back the explicitly set value of empty string rather than needing special logic that knows how to deal with `marshmallow.missing`.

If the current behavior cannot be changed e.g. for compatibility reasons, it should at least be documented, as this seems like a common use case.

Happy to submit a PR if that would be of interest. Thanks!

**Comment by sloria** [comment]
This does appear to be a bug; I'd expect an empty string to be returned instead of `marshmallow.missing.`

I can't look into it today, so would definitely appreciate a PR.

**Comment by hvtuananh** [comment]
I'll prepare a PR next week
