### ISSUE TITLE
Proxy env var to prefixed env vars

### ISSUE THREAD

**Issue by Kamforka** [sloria/environs#72]
When I proxy a non-prefixed env var to a prefixed one and try to load them an error is thrown.

### Example: 
**.env**
```
FLASK_ENV=development
APP_ENV={{FLASK_ENV}}
```

**settings.py**
```python
from environs import Env

env = Env()
env.read_env()


with env.prefixed('APP_'):
    ENV = env.str('ENV')
```

**Output:**
```bash
Traceback (most recent call last):
  File "settings.py", line 8, in <module>
    ENV = env.str('ENV')
  File "/.../venv/lib/python3.6/site-packages/environs.py", line 47, in method
    'Environment variable "{}" not set'.format(proxied_key or parsed_key)
environs.EnvError: Environment variable "FLASK_ENV" not set
```

Is it intentional to only allow proxying variables within the prefix scope?

Obviously there are many possible workarounds to fix the error, however it feels unintuitive to restrict proxying to a prefix scope.

**Comment by sloria** [comment]
This appears to be a bug. I won't have time to look at this soon, so I would definitely review and merge a PR.

**Comment by Kamforka** [comment]
@sloria Got it. I'll make a PR. Took a look at it and seems like a quick fix.
