### ISSUE TITLE
Add env.database_url

### ISSUE THREAD

**Issue by sloria** [sloria/environs#88]
Add a database URL parser method that validates that the input envvar is a valid database URL.

**Comment by epicserve** [comment]
Is this issue still valid?

**Comment by sloria** [comment]
Yeah, there is `dj_database_url` which parses into the Django-specific config dictionary, but there isn't yet a general-purpose parse that just validates the string without doing any special formatting.

**Comment by sloria** [comment]
Closing for now for lack of interest
