### ISSUE TITLE
Two proxied variables

### ISSUE THREAD

**Issue by zevisert** [sloria/environs#90]
Suppose I'm trying to construct a variable by concatenating two proxied variables...

```
VAR_A=foo
VAR_B=bar

VAR_C={{VAR_A}}_{{VAR_B}
```

Environs will fail to parse the two proxies and claim that the a joined variable is not set

```py
>>> import environs
>>> env = envions.Env()
>>> env.read_env(...)
>>> env('VAR_C') 
environs.EnvError:  Environment variable "VAR_A}}_{{VAR_B" not set
```

**Comment by sloria** [comment]
The `{{}}` syntax should only be used for proxying other envvars, not for string interpolation. That's to say that you shouldn't need to concatenate proxied variables like that.

The standard pattern with environs is to have a settings file with constants whose values come from envvars.

```python
# settings.py

VAR_A = env.str('VAR_A')
VAR_B = env.str('VAR_B')
VAR_C = f'{VAR_A}_{VAR_B}'
```

Your application would then use `settings.VAR_C`.

**Comment by zevisert** [comment]
That'll work for my use case, thanks!
