### ISSUE TITLE
When looking for a specific file, working recursively should be possible

### ISSUE THREAD

**Issue by ribeaud** [sloria/environs#96]
Up to the documentation, it is possible to read a specific file:
```
env = Env()
env.read_env(".env.test", recurse=False)
```
If I switch _recursive_ to `True`, then it will look for `.env` file and NOT for the file specified as first argument (_path_), making recursion useless in such cases.

**Comment by sloria** [comment]
Thanks for reporting. PRs welcome to address this.

**Comment by sloria** [comment]
Thanks again for the PR. It's released in 5.2.1

**Comment by ribeaud** [comment]
Hi @sloria. Unfortunately, the fix I've provided does NOT work. I did NOT test enough resp. it is not so easy to test. I will open an new issue and relate it to that one.
